version: 2
jobs:
    first:
        docker:
            -image: circleci/ruby:2.4.1
        steps:
            - checkout
            - run: echo "A first hello"
    second:
        docker:
            -image: circleci/ruby:2.4.1
        steps:
            - checkout
            - run: echo "A first hello"
    workflows:
        version: 2
        team:
            jobs:
                - first
                - second